//! Low-level core Lanczos algorithm implementations for Krylov subspace methods.
//!
//! **NOTE**: We recommend using the high-level methods the functions in [`crate::solvers`] instead.
//! This module is intended for use cases where fine-grained control over the Lanczos process is required.
//!
//! This module contains the low-level algorithm implementations that power the high-level
//! solvers. These functions are exposed publicly for:
//!
//! - Users who need fine-grained control
//! - Testing and benchmarking purposes
//! - Algorithm experimentation
//!
//! ## Standard API vs Low-level API
//!
//! **Recommended**: Use [`crate::solvers::lanczos`] and [`crate::solvers::lanczos_two_pass`]
//! for normal usage. These provide a clean, user-friendly interface.
//!
//! **Advanced**: Use functions from this module only if you need access to intermediate
//! results like the Lanczos basis matrix V_k or want to implement custom callbacks.
//!
//! ## Implementation Details
//!
//! This module implements the symmetric Lanczos process for computing f(A)b by projecting
//! the operator A onto a small Krylov subspace, yielding a tridiagonal matrix T_k.
//!
//! Two implementation strategies are provided:
//! 1. **Standard algorithm**: Stores the full orthonormal basis V_k (O(nk) memory)
//! 2. **Two-pass variant**: Avoids basis storage through regeneration (O(n) memory)
//!
//! Both algorithms operate on matrix-free linear operators ([`faer::matrix_free::LinOp`])
//! and use stack-allocated workspaces ([`MemStack`]) for temporary storage. The implementations
//! are generic over complex field types and handle numerical breakdown detection.

// Declare the submodules. The specific implementations will reside in these files.
pub mod lanczos;
pub mod lanczos_two_pass;

use crate::error::{LanczosError, LanczosErrorKind};
use faer::traits::math_utils::{mul, sub};
use faer::{
    Par,
    dyn_stack::MemStack,
    matrix_free::LinOp,
    prelude::*,
    traits::{ComplexField, RealField},
};

// All the following are common definitions used by both the one-pass and two-pass implementations.

/// A read-only, non-owning view of the tridiagonal matrix generated by the Lanczos process.
///
/// This struct provides zero-allocation access to the raw tridiagonal matrix data
/// by referencing existing slices. Its primary use is in callbacks for inspecting the
/// algorithm's state without incurring the performance penalty of data duplication or
/// cache-unfriendly pointer indirection.
#[derive(Debug)]
pub struct TridiagonalSystemView<'a, R: RealField> {
    /// The diagonal elements of the tridiagonal matrix, corresponding to the
    /// sequence of $\alpha_j$ coefficients.
    pub alphas: &'a [R],
    /// The super/sub-diagonal elements, corresponding to the sequence of $\beta_j$
    /// coefficients.
    pub betas: &'a [R],
    /// The number of iterations completed, which defines the actual dimension
    /// of the system, especially in cases of early termination due to breakdown.
    pub steps_taken: usize,
}

/// A callback function invoked at each step of the Lanczos iteration.
///
/// This provides a hook for monitoring convergence, implementing custom termination
/// criteria, or performing other diagnostics.
///
/// # Arguments
/// * `k`: The current iteration number (1-based).
/// * `v_k`: An immutable view of the $n \times k$ basis matrix $\mathbf{V}_k = [\mathbf{v}_1, \dots, \mathbf{v}_k]$
///   generated so far.
/// * `t_k_view`: A non-owning view of the tridiagonal matrix $\mathbf{T}_k$.
///
/// # Returns
/// `true` to continue the iteration, `false` to request an early stop.
pub type LanczosCallback<T> = dyn for<'a> FnMut(
    usize,
    MatRef<'a, T>,
    &'a TridiagonalSystemView<'a, <T as ComplexField>::Real>,
) -> bool;

/// Contains the scalar data defining the low-dimensional projection of the operator.
///
/// This struct holds all data necessary to define the tridiagonal system $\mathbf{T}_k$
/// and is the complete output of the first pass of the two-pass algorithm. It is
/// designed to be lightweight and cloneable.
#[derive(Debug, Clone)]
pub struct LanczosDecomposition<R: RealField> {
    /// The diagonal elements of the tridiagonal matrix ($\alpha_j$).
    pub alphas: Vec<R>,
    /// The super/sub-diagonal elements of the tridiagonal matrix ($\beta_j$).
    /// The element `betas[j-1]` corresponds to $\beta_j$ for $j = 1, \dots, \text{steps\_taken}-1$.
    /// The vector length is always `steps_taken - 1`.
    pub betas: Vec<R>,
    /// The actual number of steps performed before breakdown or completion. This may be
    /// less than the requested number of iterations.
    pub steps_taken: usize,
    /// The L2 norm of the initial vector, $\|\mathbf{b}\|_2$. This value is pre-computed and
    /// stored to avoid recomputation and is required for the final scaling of the
    /// solution vector $\mathbf{x}_k = \mathbf{V}_k f(\mathbf{T}_k) \mathbf{e}_1 \|\mathbf{b}\|_2$.
    pub b_norm: R,
}

/// Contains the complete output of the standard one-pass Lanczos algorithm.
///
/// This structure holds both the orthonormal basis vectors and the full scalar
/// decomposition, representing the complete state of the Lanczos process after $k$ steps.
#[derive(Debug)]
pub struct LanczosOutput<T: ComplexField> {
    /// The matrix $\mathbf{V}_k \in \mathbb{C}^{n \times k}$ whose columns are the orthonormal
    /// Lanczos basis vectors, $[\mathbf{v}_1, \dots, \mathbf{v}_k]$.
    /// This is the structure that incurs the $O(nk)$ memory cost.
    pub v_k: Mat<T>,
    /// The scalar data from the Lanczos process, including $\mathbf{T}_k$ and $\|\mathbf{b}\|_2$.
    pub decomposition: LanczosDecomposition<T::Real>,
}

/// Contains the output of the second pass, including the regenerated basis.
///
/// This struct is exposed only for testing purposes to allow for a direct
/// norm comparison between the stored basis from [`crate::algorithms::lanczos::lanczos_standard`] and the
/// regenerated basis.
#[derive(Debug)]
pub struct LanczosPassTwoOutput<T: ComplexField> {
    /// The final approximate solution vector $\mathbf{x}_k$.
    pub x_k: Mat<T>,
    /// The regenerated basis matrix $\mathbf{V}'_k$.
    pub v_k: Mat<T>,
}

/// Computes the tolerance for breakdown detection based on machine epsilon.
///
/// This provides better numerical robustness than hardcoded tolerances.
fn breakdown_tolerance<T: RealField>() -> T {
    // A small multiple of machine epsilon is a standard choice for breakdown detection.
    T::from_f64_impl(f64::EPSILON * 1000.0)
}

/// Performs a single, fully orthogonalized step of the Lanczos recurrence relation.
///
/// This function implements the core three-term recurrence:
/// $\beta_j \mathbf{v}_{j+1} = \mathbf{A}\mathbf{v}_j - \alpha_j \mathbf{v}_j - \beta_{j-1}\mathbf{v}_{j-1}$.
///
/// The implementation follows the standard formulation, ensuring that the newly
/// computed (unnormalized) vector is orthogonal to the two preceding basis vectors.
/// The result is written to a pre-allocated mutable view `w` to avoid heap allocations
/// within the iterative loop.
///
/// # Arguments
/// * `operator`: The linear operator $\mathbf{A}$.
/// * `w`: A pre-allocated mutable matrix view for the output vector $\mathbf{w} = \beta_j \mathbf{v}_{j+1}$.
/// * `v_curr`: The current Lanczos vector $\mathbf{v}_j$.
/// * `v_prev`: The previous Lanczos vector $\mathbf{v}_{j-1}$.
/// * `beta_prev`: The previous off-diagonal coefficient $\beta_{j-1}$.
/// * `stack`: A [`MemStack`] for temporary allocations required by the operator's `apply` method.
///
/// # Returns
/// A tuple containing $(\alpha_j, \text{Option}<\beta_j>)$. A [`None`] value for $\beta_j$ indicates
/// that a numerical breakdown has occurred ($\beta_j$ is numerically zero), and the iteration
/// should terminate. This happens when the Krylov subspace becomes invariant under $\mathbf{A}$.
fn lanczos_recurrence_step<T: ComplexField, O: LinOp<T>>(
    operator: &O,
    mut w: MatMut<'_, T>,
    v_curr: MatRef<'_, T>,
    v_prev: MatRef<'_, T>,
    beta_prev: T::Real,
    stack: &mut MemStack,
) -> (T::Real, Option<T::Real>) {
    // 1. Apply the operator: w = A * v_curr. This is typically the most
    // computationally intensive part of the step.
    operator.apply(w.rb_mut(), v_curr, Par::Seq, stack);

    // 2. First orthogonalization step (against v_{j-1}).
    // This computes w <- w - \beta_{j-1} * v_{j-1} in-place.
    // The use of `zip!` ensures that this loop can be autovectorized by the
    // compiler
    let beta_prev_scaled = T::from_real_impl(&beta_prev);
    zip!(w.rb_mut(), v_prev).for_each(|unzip!(w_i, v_prev_i)| {
        *w_i = sub(w_i, &mul(&beta_prev_scaled, v_prev_i));
    });

    // 3. Compute the diagonal element \alpha_j = v_j^H * w.
    // At this stage, w = A*v_j - \beta_{j-1}*v_{j-1}, which is the
    // intermediate vector for computing \alpha_j. Since A is Hermitian, \alpha_j is real.
    let alpha = T::real_part_impl(&(v_curr.adjoint() * w.rb())[(0, 0)]);

    // 4. Second orthogonalization step (against v_j).
    // This computes w <- w - \alpha_j * v_j in-place.
    let alpha_scaled = T::from_real_impl(&alpha);
    zip!(w.rb_mut(), v_curr).for_each(|unzip!(w_i, v_curr_i)| {
        *w_i = sub(w_i, &mul(&alpha_scaled, v_curr_i));
    });

    // 5. Compute the off-diagonal element \beta_j = ||w||_2.
    // The vector w now holds the unnormalized next Lanczos vector.
    let beta = w.rb().norm_l2();

    // 6. Check for numerical breakdown. If \beta_j is close to zero, the Krylov
    // subspace is (numerically) invariant under A, and the iteration must stop.
    let tolerance = breakdown_tolerance::<T::Real>();
    if beta <= tolerance {
        (alpha, None)
    } else {
        (alpha, Some(beta))
    }
}

/// A lightweight struct to hold the scalar results of a single Lanczos step.
struct LanczosStep<T: ComplexField> {
    /// The diagonal element $\alpha_j$.
    alpha: T::Real,
    /// The off-diagonal element $\beta_j$.
    beta: T::Real,
}

/// A private struct that encapsulates the state of the Lanczos iteration.
///
/// This struct provides a clean, stateful representation of the Lanczos recurrence,
/// abstracting away the low-level vector manipulations. It is designed as an iterator-like
/// object that can be consumed by different high-level algorithm implementations (e.g.,
/// one-pass vs. two-pass). It manages its own work vectors to avoid repeated heap
/// allocations in the main iterative loop. The use of `Mat<T>` instead of [`MatMut`]
/// for vectors means that this struct takes ownership of the vector data.
struct LanczosIteration<'a, T: ComplexField, O: LinOp<T>> {
    /// A reference to the linear operator.
    operator: &'a O,
    /// The previous Lanczos vector, $\mathbf{v}_{j-1}$.
    v_prev: Mat<T>,
    /// The current Lanczos vector, $\mathbf{v}_j$.
    v_curr: Mat<T>,
    /// A reusable work vector for intermediate computations, primarily to hold $\mathbf{A}\mathbf{v}_j$.
    work: Mat<T>,
    /// The previous beta coefficient, $\beta_{j-1}$.
    beta_prev: T::Real,
    /// The current iteration number (0-indexed internally).
    k: usize,
    /// The maximum number of iterations to perform.
    max_k: usize,
}

impl<'a, T: ComplexField, O: LinOp<T>> LanczosIteration<'a, T, O>
where
    T::Real: RealField,
{
    /// Creates a new [`LanczosIteration`] instance and prepares the initial state.
    ///
    /// # Arguments
    /// * `operator`: The linear operator to be used.
    /// * `b`: The initial vector.
    /// * `max_k`: The maximum number of iterations.
    /// * `b_norm`: The pre-computed L2 norm of `b`.
    ///
    /// # Returns
    /// A [`Result`] containing the new instance or a [`LanczosError`] if the input vector is zero.
    fn new(
        operator: &'a O,
        b: MatRef<'_, T>,
        max_k: usize,
        b_norm: T::Real,
    ) -> Result<Self, LanczosError> {
        let zero_threshold = breakdown_tolerance::<T::Real>();
        if b_norm <= zero_threshold {
            return Err(LanczosErrorKind::InputError(
                "Input vector `b` must not be a zero vector.".to_string(),
            )
            .into());
        }

        // Normalize the initial vector efficiently using the pre-computed norm.
        // This avoids a second norm calculation.
        let inv_norm = T::from_real_impl(&T::Real::recip_impl(&b_norm));
        let v1 = b * Scale(inv_norm);

        Ok(Self {
            operator,
            v_prev: Mat::zeros(b.nrows(), 1),
            v_curr: v1,
            work: Mat::zeros(b.nrows(), 1),
            beta_prev: T::Real::zero_impl(),
            k: 0,
            max_k,
        })
    }

    /// Performs the next step of the Lanczos iteration and updates the internal state.
    fn next_step(&mut self, stack: &mut MemStack) -> Option<LanczosStep<T>> {
        if self.k >= self.max_k {
            return None;
        }

        // Execute the core recurrence using the pre-allocated work vector.
        let (alpha, beta_option) = lanczos_recurrence_step(
            self.operator,
            self.work.as_mut(),
            self.v_curr.as_ref(),
            self.v_prev.as_ref(),
            T::Real::copy_impl(&self.beta_prev),
            stack,
        );

        self.k += 1;

        match beta_option {
            Some(beta) => {
                // Normalize the next Lanczos vector in-place: v_{j+1} = work / \beta_j
                let inv_beta = T::from_real_impl(&T::Real::recip_impl(&beta));
                zip!(self.work.as_mut()).for_each(|unzip!(w_i)| {
                    *w_i = mul(w_i, &inv_beta);
                });

                // Update state for the next iteration using move semantics.
                // Swapping vectors is a zero-cost operation that avoids cloning large amounts
                // of data, significantly improving performance by reducing memory traffic.
                // The logical flow is: v_prev gets v_curr's data, v_curr gets the newly computed
                // vector from `work`, and `work` gets the old v_prev's allocation to be reused.
                core::mem::swap(&mut self.v_prev, &mut self.v_curr);
                core::mem::swap(&mut self.v_curr, &mut self.work);
                self.beta_prev = T::Real::copy_impl(&beta);

                Some(LanczosStep {
                    alpha,
                    beta: T::Real::copy_impl(&beta),
                })
            }
            None => {
                // Breakdown occurred. The iteration cannot continue. Return the computed alpha
                // and a zero beta to signal termination to the caller.
                Some(LanczosStep {
                    alpha,
                    beta: T::Real::zero_impl(),
                })
            }
        }
    }
}

#[allow(dead_code)]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        algorithms::{
            lanczos::lanczos_standard,
            lanczos_two_pass::{lanczos_pass_one, lanczos_pass_two_with_basis},
        },
        utils::data_loader::load_kkt_system,
    };
    use anyhow::{Result, ensure};
    use faer::dyn_stack::MemBuffer;
    use rand::{Rng, SeedableRng, rngs::StdRng};
    use std::path::PathBuf;

    // A tolerance for floating-point comparisons in property tests.
    const TOLERANCE: f64 = 5e-9;

    /// A helper struct to hold paths to a complete test instance.
    #[derive(Debug)]
    struct TestInstance {
        pub name: String,
        pub dmx_path: PathBuf,
        pub qfc_path: PathBuf,
    }

    /// Lightweight test problem for basic unit tests.
    fn setup_simple_problem() -> (Mat<f64>, Mat<f64>) {
        let a: Mat<f64> = mat![
            [2.0, -1.0, 0.0, 0.0],
            [-1.0, 2.0, -1.0, 0.0],
            [0.0, -1.0, 2.0, -1.0],
            [0.0, 0.0, -1.0, 2.0],
        ];
        let b: Mat<f64> = mat![[1.0], [2.0], [3.0], [4.0]];
        (a, b)
    }

    // --- UNIT TESTS ---

    #[test]
    fn test_recurrence_step_correctness() {
        let (a, _) = setup_simple_problem();
        let mut mem = MemBuffer::new(a.apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let v_curr: Mat<f64> = mat![[1.0], [0.0], [0.0], [0.0]];
        let v_prev: Mat<f64> = Mat::zeros(4, 1);
        let beta_prev = 0.0;

        let mut work = Mat::<f64>::zeros(4, 1);
        let (alpha, beta_option) = lanczos_recurrence_step(
            &a.as_ref(),
            work.as_mut(),
            v_curr.as_ref(),
            v_prev.as_ref(),
            beta_prev,
            stack,
        );

        let beta = beta_option.unwrap();
        assert!((alpha - 2.0).abs() < 1e-15);
        assert!((beta - 1.0).abs() < 1e-15);
    }

    #[test]
    fn test_breakdown_scenario() {
        let a: Mat<f64> = mat![[2.0, 0.0], [0.0, 3.0]];
        let b: Mat<f64> = mat![[1.0], [0.0]];
        let k = 2;
        let mut mem = MemBuffer::new(a.apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let result = lanczos_standard(&a.as_ref(), b.as_ref(), k, stack, None).unwrap();
        assert_eq!(result.decomposition.steps_taken, 1);
    }

    #[test]
    fn test_zero_vector_input_returns_error() {
        let a: Mat<f64> = Mat::identity(2, 2);
        let b: Mat<f64> = Mat::zeros(2, 1);
        let mut mem = MemBuffer::new(a.apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);
        assert!(lanczos_standard(&a, b.as_ref(), 2, stack, None).is_err());
    }

    // --- PROPERTY TESTS (RUNNERS) ---

    /// Verifies that the scalar decompositions from the one-pass and two-pass
    /// algorithms are consistent to within floating-point tolerance.
    fn run_decomposition_consistency_test_for_instance(instance: &TestInstance) -> Result<()> {
        let k = 30;
        let kkt_system = load_kkt_system(&instance.dmx_path, &instance.qfc_path)?;
        let a = kkt_system.a;
        let n = a.nrows();
        let mut rng = StdRng::seed_from_u64(42);
        let b = Mat::from_fn(n, 1, |_, _| rng.random());
        let mut mem = MemBuffer::new(a.as_ref().apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let standard_output = lanczos_standard(&a.as_ref(), b.as_ref(), k, stack, None)?;
        let pass_one_output = lanczos_pass_one(&a.as_ref(), b.as_ref(), k, stack)?;

        ensure!(
            standard_output.decomposition.steps_taken == pass_one_output.steps_taken,
            "steps_taken mismatch on instance '{}'",
            instance.name
        );

        for (i, (alpha_std, alpha_po)) in standard_output
            .decomposition
            .alphas
            .iter()
            .zip(pass_one_output.alphas.iter())
            .enumerate()
        {
            ensure!(
                (alpha_std - alpha_po).abs() < TOLERANCE,
                "Alpha mismatch at index {} on instance '{}'",
                i,
                instance.name,
            );
        }
        for (i, (beta_std, beta_po)) in standard_output
            .decomposition
            .betas
            .iter()
            .zip(pass_one_output.betas.iter())
            .enumerate()
        {
            ensure!(
                (beta_std - beta_po).abs() < TOLERANCE,
                "Beta mismatch at index {} on instance '{}'",
                i,
                instance.name,
            );
        }
        Ok(())
    }

    /// Verifies that the fundamental Lanczos relation A*V_k - V_k*T_k = beta_k*v_{k+1}*e_k^T
    /// holds for the standard algorithm.
    fn run_lanczos_relation_test_for_instance(instance: &TestInstance) -> Result<()> {
        let k = 30;
        let kkt_system = load_kkt_system(&instance.dmx_path, &instance.qfc_path)?;
        let a = kkt_system.a;
        let n = a.nrows();
        let mut rng = StdRng::seed_from_u64(42);
        let b = Mat::from_fn(n, 1, |_, _| rng.random());
        let mut mem = MemBuffer::new(a.as_ref().apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let result_k = lanczos_standard(&a.as_ref(), b.as_ref(), k, stack, None)?;
        let result_k_plus_1 = lanczos_standard(&a.as_ref(), b.as_ref(), k + 1, stack, None)?;

        let v_k = result_k.v_k.as_ref();
        let beta_k = result_k_plus_1.decomposition.betas[k - 1];
        let v_k_plus_1 = result_k_plus_1.v_k.as_ref().get(.., k..k + 1);

        let t_k_mat = {
            let mut t = Mat::zeros(k, k);
            for i in 0..k {
                t.as_mut()[(i, i)] = result_k.decomposition.alphas[i];
            }
            for i in 0..k - 1 {
                t.as_mut()[(i, i + 1)] = result_k.decomposition.betas[i];
                t.as_mut()[(i + 1, i)] = result_k.decomposition.betas[i];
            }
            t
        };

        let mut e_k = Mat::zeros(k, 1);
        e_k.as_mut()[(k - 1, 0)] = 1.0;

        let residual_matrix = a.as_ref() * v_k - v_k * t_k_mat;
        let expected_residual_matrix = v_k_plus_1 * e_k.as_ref().adjoint() * Scale(beta_k);

        let norm_diff = (residual_matrix - expected_residual_matrix).norm_l2();
        ensure!(
            norm_diff < TOLERANCE,
            "Lanczos relation does not hold on instance '{}'. Diff norm: {}",
            instance.name,
            norm_diff
        );
        Ok(())
    }

    /// Verifies that the basis vectors generated by the standard algorithm are orthonormal.
    fn run_orthonormality_test_for_instance(instance: &TestInstance) -> Result<()> {
        let k = 30;
        let kkt_system = load_kkt_system(&instance.dmx_path, &instance.qfc_path)?;
        let a = kkt_system.a;
        let n = a.nrows();
        let mut rng = StdRng::seed_from_u64(42);
        let b = Mat::from_fn(n, 1, |_, _| rng.random());
        let mut mem = MemBuffer::new(a.as_ref().apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let standard_output = lanczos_standard(&a.as_ref(), b.as_ref(), k, stack, None)?;
        let v_k_standard = standard_output.v_k.as_ref();
        let steps = standard_output.decomposition.steps_taken;
        let identity = Mat::<f64>::identity(steps, steps);
        let ortho_error_standard = (&identity - v_k_standard.adjoint() * v_k_standard).norm_l2();
        ensure!(
            ortho_error_standard < TOLERANCE,
            "Standard basis on instance '{}' is not orthonormal. Error norm: {}",
            instance.name,
            ortho_error_standard
        );
        Ok(())
    }

    /// Verifies the numerical stability of the two-pass method by measuring the
    /// drift between the standard and regenerated Lanczos bases.
    fn run_reconstruction_stability_test_for_instance(instance: &TestInstance) -> Result<()> {
        let k = 30;
        let kkt_system = load_kkt_system(&instance.dmx_path, &instance.qfc_path)?;
        let a = kkt_system.a;
        let n = a.nrows();
        let mut rng = StdRng::seed_from_u64(42);
        let b = Mat::from_fn(n, 1, |_, _| rng.random());
        let mut mem = MemBuffer::new(a.as_ref().apply_scratch(1, Par::Seq));
        let stack = MemStack::new(&mut mem);

        let standard_output = lanczos_standard(&a.as_ref(), b.as_ref(), k, stack, None)?;
        let v_k_ref = standard_output.v_k;
        let steps = standard_output.decomposition.steps_taken;

        let decomp = lanczos_pass_one(&a.as_ref(), b.as_ref(), k, stack)?;
        let y_k = Mat::from_fn(steps, 1, |i, _| 0.1 * (i + 1) as f64);

        let pass_two_output =
            lanczos_pass_two_with_basis(&a.as_ref(), b.as_ref(), &decomp, y_k.as_ref(), stack)?;
        let v_k_regenerated = pass_two_output.v_k;

        let drift = (v_k_ref - v_k_regenerated).squared_norm_l2();
        ensure!(
            drift < TOLERANCE,
            "Numerical drift between bases on instance '{}' is too high. Drift norm: {}",
            instance.name,
            drift
        );
        Ok(())
    }

    /// Macro to generate a test module that includes all dynamically generated
    /// test functions from the build script.
    macro_rules! generate_property_tests {
        () => {
            mod generated {
                use super::*;
                include!(concat!(env!("OUT_DIR"), "/lanczos_properties_tests.rs"));
            }
        };
    }

    generate_property_tests!();
}
