#!/usr/bin/env python3

"""
Generates a plot for the dense matrix memory-computation trade-off experiment.

This script reads a CSV file produced by the `dense_tradeoff.rs` runner and
creates a single plot visualizing the wall-clock time vs. the number of
iterations (k) to confirm the dominance of matrix-vector product costs.
"""
import argparse
import pandas as pd
import matplotlib.pyplot as plt

def create_plot(input_csv_path: str, output_path: str):
    """
    Reads experiment data and generates a single execution time plot.

    # Arguments
    * `input_csv_path` - Path to the input CSV file containing the results.
    * `output_path` - The path where the output PDF file will be saved.
    """
    try:
        df = pd.read_csv(input_csv_path)
    except FileNotFoundError:
        print(f"Error: Input file not found at '{input_csv_path}'")
        return

    # Separate dataframes for each variant for easier plotting.
    df_standard = df[df['variant'] == 'standard'].copy()
    df_two_pass = df[df['variant'] == 'two-pass'].copy()

    plt.style.use('seaborn-v0_8-whitegrid')

    # --- Execution Time Plot ---
    fig_time, ax_time = plt.subplots(figsize=(8, 6))

    ax_time.plot(
        df_standard["k"],
        df_standard["time_s"],
        label="Standard Lanczos (One-Pass)",
        marker='o',
        linestyle='-',
        color='C0'
    )
    ax_time.plot(
        df_two_pass["k"],
        df_two_pass["time_s"],
        label="Two-Pass Lanczos",
        marker='x',
        linestyle='--',
        color='C1'
    )

    ax_time.set_xlabel("Number of Iterations (k)", fontsize=12)
    ax_time.set_ylabel("Wall-Clock Time (seconds)", fontsize=12)
    ax_time.set_title("Execution Time vs. Iteration Count (Dense Matrix)", fontsize=14, fontweight='bold')
    ax_time.legend(fontsize=11)
    ax_time.tick_params(axis='both', which='major', labelsize=10)
    ax_time.grid(True, which='both', linestyle='--', linewidth=0.5)

    fig_time.savefig(output_path, bbox_inches='tight')
    print(f"Successfully saved time plot to: {output_path}")
    plt.close(fig_time)

def main():
    """Parses command-line arguments and runs the plotting function."""
    parser = argparse.ArgumentParser(
        description="Plot results for the dense Lanczos trade-off experiment."
    )
    parser.add_argument(
        "--input",
        type=str,
        required=True,
        help="Path to the input CSV file generated by the dense_tradeoff runner."
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        help="Path for the output PDF plot file."
    )
    args = parser.parse_args()
    create_plot(args.input, args.output)

if __name__ == "__main__":
    main()
